/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petproj_ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author win10
 */
public class customerplaceorder extends javax.swing.JFrame {

    /**
     * Creates new form customerplaceorder
     */
    public customerplaceorder() {
        initComponents();
        logenter();
        calc();
        orderpanel.setVisible(false);
        changem.setVisible(false);
        portall.setVisible(false);
       
    }
String ename=null;
boolean statchoice=false;
//ArrayList<String> plst=new ArrayList<String>();
//ArrayList<Integer> clst=new ArrayList<Integer>();
//String pincode=null;
 String pmethod=null;   
private void logenter(){
          String logname=null;
          String pc=null;
          try{
              Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3307/petshop","root","amgroot");
		Statement stmt=con.createStatement();
                String sql3="select * from atlogs";
                ResultSet rsx=stmt.executeQuery(sql3);
                while(rsx.next()){
                    logname=rsx.getString(2);
                    
                }
                ename=logname;
          }catch(Exception ex){
              ex.printStackTrace();
          }
      }
private void calc(){
    String ol=" ";
    int total=0;
    try{
        Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3307/petshop","root","amgroot");
		Statement stmt=con.createStatement();
                String sql="select * from cart where cname='"+ename+"'";
                ResultSet rsx=stmt.executeQuery(sql);
                while(rsx.next()){
                   String appe=rsx.getString(2);
                  // plst.add(appe);
                   
                   ol=ol+" "+appe;
                   int x=Integer.parseInt(rsx.getString(3));
                   //clst.add(x);
                   total=total+x;
                   namel.setText("NAME: "+ename);
                   listl.setText("LIST : "+ol);
                   totalcostl.setText("TOTAL COST:" +total);
                }
    }catch(Exception e){
        e.printStackTrace();
    }
}
private void paystatcheck(){
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namel = new javax.swing.JLabel();
        listl = new javax.swing.JLabel();
        totalcostl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cod = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        card = new javax.swing.JLabel();
        changem = new javax.swing.JButton();
        orderpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        portall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petproj_ui/icons8-shopping-cart-50.png"))); // NOI18N
        jLabel1.setText("VIEW CART");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namel.setText("NAME:                                                                 ");

        listl.setText("LIST:                                                   ");

        totalcostl.setText("TOTAL COST:                                  ");

        jLabel2.setText("PAYMENT METHOD");

        cod.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cod.setText("CASH ON DELIVERY");
        cod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                codMousePressed(evt);
            }
        });

        card.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        card.setText("DEBIT/CREDIT CARD");
        card.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        card.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cardMousePressed(evt);
            }
        });

        changem.setText("Change payment method");
        changem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                changemMousePressed(evt);
            }
        });

        orderpanel.setBackground(new java.awt.Color(0, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("                PLACE ORDER");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout orderpanelLayout = new javax.swing.GroupLayout(orderpanel);
        orderpanel.setLayout(orderpanelLayout);
        orderpanelLayout.setHorizontalGroup(
            orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );
        orderpanelLayout.setVerticalGroup(
            orderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setText("back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        portall.setText("GO TO PORTAL");
        portall.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        portall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        portall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                portallMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalcostl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(listl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(card, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(changem)
                                    .addComponent(portall))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(orderpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namel)
                        .addGap(18, 18, 18)
                        .addComponent(listl)
                        .addGap(18, 18, 18)
                        .addComponent(totalcostl))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(cod))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(changem)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(card)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                .addComponent(orderpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(portall)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new customermenu().show();
    }//GEN-LAST:event_jButton2MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new viewcart().show();
    }//GEN-LAST:event_jLabel1MousePressed

    private void codMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codMousePressed
        // TODO add your handling code here:
        pmethod=cod.getText();
        card.setVisible(false);
        changem.setVisible(true);
        orderpanel.setVisible(true);
    }//GEN-LAST:event_codMousePressed

    private void cardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardMousePressed
        // TODO add your handling code here:
        pmethod=card.getText();
        cod.setVisible(false);
        changem.setVisible(true);
        //orderpanel.setVisible(true);
        portall.setVisible(true);
       // paypanel.setVisible(true);
        //statchoice=true;
    }//GEN-LAST:event_cardMousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        boolean stat=false;
        boolean stat1=false;
        String pincode=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3307/petshop","root","amgroot");
		Statement stmt=con.createStatement();
                Statement stmt1=con.createStatement();
                Statement stmt3=con.createStatement();
                 Statement stmt2=con.createStatement();
                String sql3="select * from cart where cname='"+ename+"'";
                ResultSet rsx=stmt3.executeQuery(sql3);
                String sql="select pcode from user where uname='"+ename+"'";
                ResultSet rs=stmt1.executeQuery(sql);
                if(rs.next()){
                    //int i=0;
                    //int j=0;
                    
                    pincode=rs.getString(1);
                    //JOptionPane.showMessageDialog(null,"pincoe:"+pincode);   
                }
           
                    while(rsx.next()){
                       String pname=null;
                    String pcost=null;
                    String cid=null;
                           pname=rsx.getString(2);
                           pcost=rsx.getString(3);
                           cid=rsx.getString(4);
                          // i++;
                          // JOptionPane.showMessageDialog(null,"PET: ORDER:"+ename+" "+pname+" "+pcost+" "+pincode);
                          String sql1= " insert into orders(cname,petname,price,pincode) values('"+ename+"','"+pname+"','"+pcost+"','"+pincode+"')"; 
                          stmt1.executeUpdate(sql1);
                         // JOptionPane.showMessageDialog(null,"ORDER:"+ename+" "+pname+" "+pcost+" "+pincode+" done");
                         stat=true;
                          
                          if(stat){
                   
                String sql2="delete from cart where cid='"+cid+"'";
                stmt2.executeUpdate(sql2);
                
                }
                        
                    
        }
                stat1=true;
               if(stat1){
                   JOptionPane.showMessageDialog(null," order placed");
                   this.setVisible(false);
                   new customerorderviewer().show();
               } 
              
             
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabel3MousePressed

    private void changemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changemMousePressed
        // TODO add your handling code here:
        cod.setVisible(true);
        card.setVisible(true);
        orderpanel.setVisible(false);
        changem.setVisible(false);
    }//GEN-LAST:event_changemMousePressed

    private void portallMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_portallMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new cardportal().show();
    }//GEN-LAST:event_portallMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerplaceorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerplaceorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerplaceorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerplaceorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerplaceorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel card;
    private javax.swing.JButton changem;
    private javax.swing.JLabel cod;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel listl;
    private javax.swing.JLabel namel;
    private javax.swing.JPanel orderpanel;
    private javax.swing.JLabel portall;
    private javax.swing.JLabel totalcostl;
    // End of variables declaration//GEN-END:variables
}
