/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petproj_ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author User
 */
public class placeorder extends javax.swing.JFrame {
String selection=null;
    /**
     * Creates new form placeorder
     */
    public placeorder() {
        initComponents();
        jButton2.setVisible(false);
        logenter();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        pincodetf = new javax.swing.JTextField();
        petnametf = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tabby = new javax.swing.JLabel();
        munchkin = new javax.swing.JLabel();
        fold = new javax.swing.JLabel();
        calico = new javax.swing.JLabel();
        curl = new javax.swing.JLabel();
        persian = new javax.swing.JLabel();
        husky = new javax.swing.JLabel();
        pitbull = new javax.swing.JLabel();
        german = new javax.swing.JLabel();
        gldrtr = new javax.swing.JLabel();
        greyh = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("NAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("PINCODE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("PETNAME ");

        nametf.setEditable(false);
        nametf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        pincodetf.setEditable(false);
        pincodetf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pincodetf.setBorder(null);

        petnametf.setEditable(false);
        petnametf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        petnametf.setBorder(null);

        jButton2.setText("SUBMIT");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jLabel4.setText("SELECT:");

        jLabel5.setText("CATS:");

        jLabel6.setText("DOGS");

        tabby.setBackground(new java.awt.Color(0, 153, 255));
        tabby.setText("Tabby");
        tabby.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabby.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabbyMousePressed(evt);
            }
        });

        munchkin.setBackground(new java.awt.Color(0, 153, 255));
        munchkin.setText("Munchkin");
        munchkin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        munchkin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                munchkinMousePressed(evt);
            }
        });

        fold.setBackground(new java.awt.Color(0, 153, 255));
        fold.setText("Scottish Fold");
        fold.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                foldMousePressed(evt);
            }
        });

        calico.setBackground(new java.awt.Color(0, 153, 255));
        calico.setText("Calico");
        calico.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        calico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calicoMousePressed(evt);
            }
        });

        curl.setBackground(new java.awt.Color(0, 153, 255));
        curl.setText("American Curl");
        curl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        curl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                curlMousePressed(evt);
            }
        });

        persian.setBackground(new java.awt.Color(0, 153, 255));
        persian.setText("Persian");
        persian.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        persian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                persianMousePressed(evt);
            }
        });

        husky.setBackground(new java.awt.Color(0, 153, 255));
        husky.setText("Husky");
        husky.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        husky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                huskyMousePressed(evt);
            }
        });

        pitbull.setBackground(new java.awt.Color(0, 153, 255));
        pitbull.setText("Pitbull");
        pitbull.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pitbull.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pitbullMousePressed(evt);
            }
        });

        german.setBackground(new java.awt.Color(0, 153, 255));
        german.setText("German Shepherd");
        german.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        german.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                germanMousePressed(evt);
            }
        });

        gldrtr.setBackground(new java.awt.Color(0, 153, 255));
        gldrtr.setText("Golden Retriever");
        gldrtr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gldrtr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gldrtrMousePressed(evt);
            }
        });

        greyh.setBackground(new java.awt.Color(0, 153, 255));
        greyh.setText("Greyhound");
        greyh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        greyh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                greyhMousePressed(evt);
            }
        });

        jButton3.setText("cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("NOTE: THE NAME MUST BE A VALID REGISTERED USER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(160, 160, 160)
                        .addComponent(jButton1)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(tabby))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(husky)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(munchkin)
                                        .addGap(18, 18, 18)
                                        .addComponent(fold)
                                        .addGap(18, 18, 18)
                                        .addComponent(calico)
                                        .addGap(18, 18, 18)
                                        .addComponent(curl)
                                        .addGap(18, 18, 18)
                                        .addComponent(persian))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pitbull)
                                        .addGap(18, 18, 18)
                                        .addComponent(german)
                                        .addGap(18, 18, 18)
                                        .addComponent(gldrtr)
                                        .addGap(18, 18, 18)
                                        .addComponent(greyh)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pincodetf, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                        .addComponent(petnametf, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pincodetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petnametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tabby)
                    .addComponent(munchkin)
                    .addComponent(fold)
                    .addComponent(calico)
                    .addComponent(curl)
                    .addComponent(persian))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(husky)
                    .addComponent(pitbull)
                    .addComponent(german)
                    .addComponent(gldrtr)
                    .addComponent(greyh))
                .addGap(40, 40, 40)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        int i=0;
        String snameo=nametf.getText();
        String sname=snameo.trim();
        //String phno=phonetf.getText();
        String pcodeo=pincodetf.getText();
        String pcode=pcodeo.trim();
        //String statev=petnametf.getText();
        String petname=petnametf.getText();
        if(statcheck())
        { 
          String price=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3307/petshop","root","amgroot");
		Statement stmt=con.createStatement();
                Statement stmt2=con.createStatement();
                Statement stmt3=con.createStatement();
                String sql2="select * from pet";
                
                
                
               // JOptionPane.showMessageDialog(null,"check"+i++);
                ResultSet rs=stmt2.executeQuery(sql2);
               // JOptionPane.showMessageDialog(null,"check"+i++);
                while(rs.next())
                {  // JOptionPane.showMessageDialog(null,"check"+i++);
                    String nm=rs.getString(3);
                    //JOptionPane.showMessageDialog(null,"nm "+nm);
                  //  JOptionPane.showMessageDialog(null,"snm "+petname);
                    if(nm.equals(petname)){
                    //    JOptionPane.showMessageDialog(null,"check"+i++);
                        price=rs.getString(5);
                      //  JOptionPane.showMessageDialog(null,"check"+i++);
                    }
                }
               // JOptionPane.showMessageDialog(null,"check ext"+i++);
                String sql="insert into orders(cname,petname,price,pincode) values('"+sname+"','"+petname+"','"+price+"','"+pcode+"')";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Done");
                
        }catch(Exception ex){
            ex.printStackTrace();
        }
          
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Retry with valid inputs");
    }
    }//GEN-LAST:event_jButton2MousePressed

    private void tabbyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbyMousePressed
        // TODO add your handling code here:
        tabby.setVisible(true);
        munchkin.setVisible(false);
        calico.setVisible(false);
        fold.setVisible(false);
        curl.setVisible(false);
        persian.setVisible(false);
        husky.setVisible(false);
        pitbull.setVisible(false);
        german.setVisible(false);
        gldrtr.setVisible(false);
        greyh.setVisible(false);
        selection=tabby.getText();
        petnametf.setText(selection);
        statcheck();
    }//GEN-LAST:event_tabbyMousePressed

    private void munchkinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_munchkinMousePressed
        // TODO add your handling code here:
        tabby.setVisible(false);
        munchkin.setVisible(true);
        calico.setVisible(false);
        fold.setVisible(false);
        curl.setVisible(false);
        persian.setVisible(false);
        husky.setVisible(false);
        pitbull.setVisible(false);
        german.setVisible(false);
        gldrtr.setVisible(false);
        greyh.setVisible(false);
        selection=munchkin.getText();
        petnametf.setText(selection);
        statcheck();
    }//GEN-LAST:event_munchkinMousePressed

    private void foldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foldMousePressed
        // TODO add your handling code here:
        tabby.setVisible(false);
        munchkin.setVisible(false);
        calico.setVisible(false);
        fold.setVisible(true);
        curl.setVisible(false);
        persian.setVisible(false);
        husky.setVisible(false);
        pitbull.setVisible(false);
        german.setVisible(false);
        gldrtr.setVisible(false);
        greyh.setVisible(false);
        selection=fold.getText();
        petnametf.setText(selection);
        statcheck();
    }//GEN-LAST:event_foldMousePressed

    private void calicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calicoMousePressed
        // TODO add your handling code here:
        tabby.setVisible(false);
        munchkin.setVisible(false);
        calico.setVisible(true);
        fold.setVisible(false);
        curl.setVisible(false);
        persian.setVisible(false);
        husky.setVisible(false);
        pitbull.setVisible(false);
        german.setVisible(false);
        gldrtr.setVisible(false);
        greyh.setVisible(false);
        selection=calico.getText();
        petnametf.setText(selection);
        statcheck();
    }//GEN-LAST:event_calicoMousePressed

    private void curlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curlMousePressed
        // TODO add your handling code here:
        tabby.setVisible(false);
        munchkin.setVisible(false);
        calico.setVisible(false);
        fold.setVisible(false);
        curl.setVisible(true);
        persian.setVisible(false);
        husky.setVisible(false);
        pitbull.setVisible(false);
        german.setVisible(false);
        gldrtr.setVisible(false);
        greyh.setVisible(false);
        selection=curl.getText();
        petnametf.setText(selection);
        statcheck();
    }//GEN-LAST:event_curlMousePressed

    private void persianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persianMousePressed
        // TODO add your handling code here:
        tabby.setVisible(false);
        munchkin.setVisible(false);
        calico.setVisible(false);
        fold.setVisible(false);
        curl.setVisible(false);
        persian.setVisible(true);
        husky.setVisible(false);
        pitbull.setVisible(false);
        german.setVisible(false);
        gldrtr.setVisible(false);
        greyh.setVisible(false);
        selection=persian.getText();
        petnametf.setText(selection);
        statcheck();
    }//GEN-LAST:event_persianMousePressed

    private void huskyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_huskyMousePressed
        // TODO add your handling code here:
        tabby.setVisible(false);
        munchkin.setVisible(false);
        calico.setVisible(false);
        fold.setVisible(false);
        curl.setVisible(false);
        persian.setVisible(false);
        husky.setVisible(true);
        pitbull.setVisible(false);
        german.setVisible(false);
        gldrtr.setVisible(false);
        greyh.setVisible(false);
        selection=husky.getText();
        petnametf.setText(selection);
        statcheck();
    }//GEN-LAST:event_huskyMousePressed

    private void pitbullMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pitbullMousePressed
        // TODO add your handling code here:
        tabby.setVisible(false);
        munchkin.setVisible(false);
        calico.setVisible(false);
        fold.setVisible(false);
        curl.setVisible(false);
        persian.setVisible(false);
        husky.setVisible(false);
        pitbull.setVisible(true);
        german.setVisible(false);
        gldrtr.setVisible(false);
        greyh.setVisible(false);
        selection=pitbull.getText();
        petnametf.setText(selection);
        statcheck();
    }//GEN-LAST:event_pitbullMousePressed

    private void germanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_germanMousePressed
        // TODO add your handling code here:
        tabby.setVisible(false);
        munchkin.setVisible(false);
        calico.setVisible(false);
        fold.setVisible(false);
        curl.setVisible(false);
        persian.setVisible(false);
        husky.setVisible(false);
        pitbull.setVisible(false);
        german.setVisible(true);
        gldrtr.setVisible(false);
        greyh.setVisible(false);
        selection=german.getText();
        petnametf.setText(selection);
        statcheck();
    }//GEN-LAST:event_germanMousePressed

    private void gldrtrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gldrtrMousePressed
        // TODO add your handling code here:
        tabby.setVisible(false);
        munchkin.setVisible(false);
        calico.setVisible(false);
        fold.setVisible(false);
        curl.setVisible(false);
        persian.setVisible(false);
        husky.setVisible(false);
        pitbull.setVisible(false);
        german.setVisible(false);
        gldrtr.setVisible(true);
        greyh.setVisible(false);
        selection=gldrtr.getText();
        petnametf.setText(selection);
        statcheck();
    }//GEN-LAST:event_gldrtrMousePressed

    private void greyhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greyhMousePressed
        // TODO add your handling code here:
        tabby.setVisible(false);
        munchkin.setVisible(false);
        calico.setVisible(false);
        fold.setVisible(false);
        curl.setVisible(false);
        persian.setVisible(false);
        husky.setVisible(false);
        pitbull.setVisible(false);
        german.setVisible(false);
        gldrtr.setVisible(false);
        greyh.setVisible(true);
        selection=greyh.getText();
        petnametf.setText(selection);
        statcheck();
    }//GEN-LAST:event_greyhMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        tabby.setVisible(true);
        munchkin.setVisible(true);
        calico.setVisible(true);
        fold.setVisible(true);
        curl.setVisible(true);
        persian.setVisible(true);
        husky.setVisible(true);
        pitbull.setVisible(true);
        german.setVisible(true);
        gldrtr.setVisible(true);
        greyh.setVisible(true);
        selection=null;
        petnametf.setText(selection);
        jButton2.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
      private boolean statcheck()
      {   String nm=nametf.getText().trim();
          String pc=null;
          if(nm==null||nm.equals("")||nm.equals(" ")){
             JOptionPane.showMessageDialog(null,"Enter name first"); 
             return(false);
          }else{
          try{
          Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3307/petshop","root","amgroot");
		Statement stmt=con.createStatement();
                String sql3="select * from user where uname='"+nm+"'";
                ResultSet rsx=stmt.executeQuery(sql3);
                if(rsx.next()){
                    String name=rsx.getString(2);
                    if(name.equals(nm)){
                        pc=rsx.getString(6);
                        pincodetf.setText(pc);
                        
                    }
                }
      }catch(Exception ex){
          ex.printStackTrace();
      }
          if(nm==null||nm.equals("")||nm.equals(" ")||pc==null||pc.equals("")||pc.equals(" ")){
              jButton2.setVisible(false);
             JOptionPane.showMessageDialog(null,"No such username found"); 
             return(false);
          }else{
              jButton2.setVisible(true);
              return(true);
          }
          }
      }
      private void logenter(){
          String logname=null;
          try{
              Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3307/petshop","root","amgroot");
		Statement stmt=con.createStatement();
                String sql3="select * from atlogs";
                ResultSet rsx=stmt.executeQuery(sql3);
                while(rsx.next()){
                    logname=rsx.getString(2);
                }
                nametf.setText(logname);
          }catch(Exception ex){
              ex.printStackTrace();
          }
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(placeorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(placeorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(placeorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(placeorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new placeorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calico;
    private javax.swing.JLabel curl;
    private javax.swing.JLabel fold;
    private javax.swing.JLabel german;
    private javax.swing.JLabel gldrtr;
    private javax.swing.JLabel greyh;
    private javax.swing.JLabel husky;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel munchkin;
    private javax.swing.JTextField nametf;
    private javax.swing.JLabel persian;
    private javax.swing.JTextField petnametf;
    private javax.swing.JTextField pincodetf;
    private javax.swing.JLabel pitbull;
    private javax.swing.JLabel tabby;
    // End of variables declaration//GEN-END:variables
}
