/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petproj_ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author win10
 */
public class viewcart extends javax.swing.JFrame {

    /**
     * Creates new form viewcart
     */
    public viewcart() {
        initComponents();
        tabby.setVisible(false);
        munchkin.setVisible(false);
        fold.setVisible(false);
        calico.setVisible(false);
        curl.setVisible(false);
        persian.setVisible(false);
        husky.setVisible(false);
        pitbull.setVisible(false);
        gldrtr.setVisible(false);
        german.setVisible(false);
        greyh.setVisible(false);
        
                
        logenter();
        calc();
    }
String ename=null;
    
private void logenter(){
          String logname=null;
          try{
              Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3307/petshop","root","amgroot");
		Statement stmt=con.createStatement();
                String sql3="select * from atlogs";
                ResultSet rsx=stmt.executeQuery(sql3);
                while(rsx.next()){
                    logname=rsx.getString(2);
                }
                ename=logname;
          }catch(Exception ex){
              ex.printStackTrace();
          }
      }
private void calc(){
    String ol=" ";
    int total=0;
    try{
        Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3307/petshop","root","amgroot");
		Statement stmt=con.createStatement();
                String sql="select * from cart where cname='"+ename+"'";
                ResultSet rsx=stmt.executeQuery(sql);
                while(rsx.next()){
                   String appe=rsx.getString(2);
                   if(appe.equals("Tabby")){
                       tabby.setVisible(true);
                   }
                   if(appe.equals("Munchkin")){
                       munchkin.setVisible(true);
                   }
                   if(appe.equals("Scottish Fold")){
                       fold.setVisible(true);
                   }
                   if(appe.equals("Calico")){
                       calico.setVisible(true);
                   }
                   if(appe.equals("American Curl")){
                       curl.setVisible(true);
                   }
                   if(appe.equals("Persian")){
                       persian.setVisible(true);
                   }
                   if(appe.equals("Husky")){
                       husky.setVisible(true);
                   }
                   if(appe.equals("Pitbull")){
                       pitbull.setVisible(true);
                   }
                   if(appe.equals("Golden Retriever")){
                       gldrtr.setVisible(true);
                   }
                   if(appe.equals("German Shepherd")){
                       german.setVisible(true);
                   }
                   if(appe.equals("Greyhound")){
                       greyh.setVisible(true);
                   }
                   ol=ol+" "+appe;
                   int x=Integer.parseInt(rsx.getString(3));
                   total=total+x;
                   namel.setText("Name: "+ename);
                   ordersl.setText("LIST : "+ol);
                   costl.setText("Total cost:" +total);
                }
    }catch(Exception e){
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namel = new javax.swing.JLabel();
        ordersl = new javax.swing.JLabel();
        greyh = new javax.swing.JLabel();
        tabby = new javax.swing.JLabel();
        munchkin = new javax.swing.JLabel();
        fold = new javax.swing.JLabel();
        calico = new javax.swing.JLabel();
        curl = new javax.swing.JLabel();
        persian = new javax.swing.JLabel();
        husky = new javax.swing.JLabel();
        pitbull = new javax.swing.JLabel();
        gldrtr = new javax.swing.JLabel();
        german = new javax.swing.JLabel();
        costl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        namel.setText("NAME:");
        getContentPane().add(namel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        ordersl.setText("ORDERS:");
        getContentPane().add(ordersl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        greyh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petproj_ui/minres_greyh.jpg"))); // NOI18N
        getContentPane().add(greyh, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 90, 90));

        tabby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petproj_ui/minres_tabby.jpg"))); // NOI18N
        getContentPane().add(tabby, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 90));

        munchkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petproj_ui/minres_munchkin.jpg"))); // NOI18N
        getContentPane().add(munchkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 90, 90));

        fold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petproj_ui/minres_fold.jpg"))); // NOI18N
        getContentPane().add(fold, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 90, 90));

        calico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petproj_ui/minres_calico.jpg"))); // NOI18N
        getContentPane().add(calico, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 120, 100));

        curl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petproj_ui/minres_curl.jpg"))); // NOI18N
        getContentPane().add(curl, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 110, 90));

        persian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petproj_ui/minres_persian.jpg"))); // NOI18N
        getContentPane().add(persian, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 90, 90));

        husky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petproj_ui/minres_husky.jpg"))); // NOI18N
        getContentPane().add(husky, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 90, 90));

        pitbull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petproj_ui/minres_pitbull.jpg"))); // NOI18N
        getContentPane().add(pitbull, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 90, 90));

        gldrtr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petproj_ui/minres_gldrtr.jpg"))); // NOI18N
        getContentPane().add(gldrtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 90, 90));

        german.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petproj_ui/minres_german.jpg"))); // NOI18N
        getContentPane().add(german, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 90, 90));

        costl.setText("TOTAL COST:");
        getContentPane().add(costl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jButton1.setText("back to shopping");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, -1));

        jButton2.setText("proceed to checkout");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, -1, -1));

        jButton3.setText("back to menu");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        jButton4.setText("clear cart");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new buypets().show();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new customermenu().show();
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3307/petshop","root","amgroot");
		Statement stmt=con.createStatement();
                String sql="delete from cart where cname='"+ename+"'";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Cleared cart");
                ordersl.setText("LIST : EMPTY");
                costl.setText("Toatal Cost:0");
                 tabby.setVisible(false);
        munchkin.setVisible(false);
        fold.setVisible(false);
        calico.setVisible(false);
        curl.setVisible(false);
        persian.setVisible(false);
        husky.setVisible(false);
        pitbull.setVisible(false);
        gldrtr.setVisible(false);
        german.setVisible(false);
        greyh.setVisible(false);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        new customerplaceorder().show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewcart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewcart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewcart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewcart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewcart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calico;
    private javax.swing.JLabel costl;
    private javax.swing.JLabel curl;
    private javax.swing.JLabel fold;
    private javax.swing.JLabel german;
    private javax.swing.JLabel gldrtr;
    private javax.swing.JLabel greyh;
    private javax.swing.JLabel husky;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel munchkin;
    private javax.swing.JLabel namel;
    private javax.swing.JLabel ordersl;
    private javax.swing.JLabel persian;
    private javax.swing.JLabel pitbull;
    private javax.swing.JLabel tabby;
    // End of variables declaration//GEN-END:variables
}
